// Theme tokens for the 5 greeting styles
export const THEMES = {
  romantic: {
    key: "romantic",
    name: "Romantic",
    vibe: "Soft · Intimate · Timeless",
    bg: "#FDFBF7",
    surface: "#F4E7E7",
    text: "#4A1525",
    sub: "#8B5F6D",
    accent: "#D19CA8",
    headingClass: "font-romantic-h",
    bodyClass: "font-romantic-b",
    radius: "rounded-3xl",
    btnRadius: "rounded-full",
    spring: { type: "tween", duration: 0.9, ease: [0.22, 1, 0.36, 1] },
  },
  elegant: {
    key: "elegant",
    name: "Elegant",
    vibe: "Classic · Sophisticated · Celebratory",
    bg: "#FFFFF0",
    surface: "#FFFFFF",
    text: "#1A1A1A",
    sub: "#4D4D4D",
    accent: "#C5A880",
    headingClass: "font-elegant-h",
    bodyClass: "font-elegant-b",
    radius: "rounded-sm",
    btnRadius: "rounded-sm",
    spring: { type: "tween", duration: 0.7, ease: [0.4, 0, 0.2, 1] },
  },
  playful: {
    key: "playful",
    name: "Playful",
    vibe: "Fun · Energetic · Youthful",
    bg: "#FCEEAA",
    surface: "#FFFFFF",
    text: "#1C1C1C",
    sub: "#4A4A4A",
    accent: "#FF8B3D",
    headingClass: "font-playful-h",
    bodyClass: "font-playful-b",
    radius: "rounded-[2rem]",
    btnRadius: "rounded-full",
    spring: { type: "spring", stiffness: 220, damping: 14 },
  },
  minimalist: {
    key: "minimalist",
    name: "Minimalist",
    vibe: "Editorial · Stark · Architectural",
    bg: "#FFFFFF",
    surface: "#F3F4F6",
    text: "#000000",
    sub: "#6B7280",
    accent: "#000000",
    headingClass: "font-minimalist-h",
    bodyClass: "font-minimalist-b",
    radius: "rounded-none",
    btnRadius: "rounded-none",
    spring: { type: "tween", duration: 0.5, ease: [0.16, 1, 0.3, 1] },
  },
  luxury: {
    key: "luxury",
    name: "Luxury",
    vibe: "Cinematic · Moody · Expensive",
    bg: "#064734",
    surface: "#042D21",
    text: "#F9F6F0",
    sub: "#9EAFA8",
    accent: "#D4AF37",
    headingClass: "font-luxury-h",
    bodyClass: "font-luxury-b",
    radius: "rounded-sm",
    btnRadius: "rounded-sm",
    spring: { type: "tween", duration: 1.1, ease: [0.22, 1, 0.36, 1] },
  },
};

export const THEME_LIST = Object.values(THEMES);

export const MUSIC_TRACKS = [
  {
    id: "soft-piano",
    name: "Soft Piano (Romantic)",
    url: "https://cdn.pixabay.com/audio/2024/01/04/audio_4c98b62ff7.mp3",
  },
  {
    id: "happy-bday",
    name: "Birthday Cheer (Playful)",
    url: "https://cdn.pixabay.com/audio/2022/05/27/audio_1808fbf07a.mp3",
  },
  {
    id: "ambient",
    name: "Cinematic Ambient (Luxury)",
    url: "https://cdn.pixabay.com/audio/2022/08/04/audio_2dde668ca0.mp3",
  },
];

export const SAMPLE_PHOTOS = [
  "https://images.pexels.com/photos/32195305/pexels-photo-32195305.jpeg",
  "https://images.pexels.com/photos/4839700/pexels-photo-4839700.jpeg",
  "https://images.pexels.com/photos/33038876/pexels-photo-33038876.jpeg",
  "https://images.pexels.com/photos/16648548/pexels-photo-16648548.jpeg",
  "https://images.pexels.com/photos/15601570/pexels-photo-15601570.jpeg",
  "https://images.pexels.com/photos/30637510/pexels-photo-30637510.jpeg",
];
